name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'


categories:
- title: 'ğŸ’¥ Breaking Changes'
  labels:
  - breaking-change
- title: 'ğŸ’¡ New Features'
  labels:
  - feature
  - enhancement
- title: 'ğŸ Bug Fixes'
  labels:
  - bug
  - fix
  - bugfix
- title: 'âš™ï¸ Technical Debt'
  labels:
  - refactor
- title: 'ğŸ“ Documentation'
  labels:
  - documentation

change-template: |
  - (#$NUMBER) $TITLE by @$AUTHOR

no-changes-template: 'No significant changes'

template: |
  ## ğŸš€ Release

  ### What's Changed
  $CHANGES

  ---

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

version-resolver:
  major:
    labels:
    - major
  minor:
    labels:
    - minor
  patch:
    labels:
    - patch
  default: patch
