name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'


categories:
  - title: 'ğŸ’¥ Breaking Changes'
    labels:
      - breaking-change
  - title: 'ğŸš€ New Features'
    labels:
      - feature
      - enhancement
  - title: 'ğŸ› Bug Fixes'
    labels:
      - bug
      - fix
      - bugfix
  - title: 'ğŸ› ï¸ Technical Debt'
    labels:
      - refactor

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'No significant changes'

template: |
  ## ğŸš€ Release

  ### What's Changed
  $CHANGES

  **Contributors:** $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch
