---

name: Automatic PR Labeler

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened]

jobs:
  assign-labels:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/auto-labeler.yaml@main
    name: Assign labels in pull request
    if: github.event.pull_request.merged == false
    with:
      pull_request_number: ${{ github.event.pull_request.number }}
      config_file: './.github/auto-labeler-config.yaml'
