---

  # This GitHub Actions workflow is designed to be triggered when
  # a release is marked as a full release.
  # The workflow performs the following tasks:
  # - Extract Release Version: Extracts the tag name and removes
  #   the leading 'v' character to get the release version.
  # - Update pom.xml: Updates the version in the pom.xml file
  #   using the extracted release version.
  # - Publish to Maven: Publishes the artifact to the Maven Central
  #   repository using the updated pom.xml.
  
name: Upload Release to Maven Central

on:
  release:
    types:
      - released
  repository_dispatch:
    types:
      - maven-publication-trigger
  
jobs:
  get_release_version:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_release_version_from_tag.outputs.release_version || steps.get_release_version_from_dispatch.outputs.release_version }}
    steps:
      - name: Get release version from release tag
        if: ${{ github.event_name == 'release' && github.event.action == 'released' }}
        id: get_release_version_from_tag
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          RELEASE_VERSION="${TAG_NAME#v}"
          echo "${RELEASE_VERSION}"
          echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
      - name: Get release version from repository dispatch
        if: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.release_version }}
        id: get_release_version_from_dispatch
        run: |
          RELEASE_VERSION="${{ github.event.client_payload.release_version }}"
          echo "${RELEASE_VERSION}"
          echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

  upload_to_maven_central:
    uses: Netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    needs: [get_release_version]
    with:
      maven_command: "--batch-mode deploy"
      java_version: '21'
      revision: ${{ needs.get_release_version.outputs.release_version }}
    secrets:
      maven_username: ${{ secrets.MAVEN_USER }}
      maven_password: ${{ secrets.MAVEN_PASSWORD }}
      maven_gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      maven_gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
  